### PR TITLE
Remove Sensitive Information from Debug Report

### PR DESCRIPTION
**Pull request by philippwaller**
This PR removes sensitive information from the debug report, focusing on the following fields:

- positionLong
- positionLat
- positionHeading

These fields are now sanitized from the debug reports to ensure that no sensitive location data is exposed.

### CODE REVIEW

**Comment by ReneNulschDE** [comment]
Removing only one attribute long or lat should be enough to protect the user. To have one attribute available for the analysis would be better.

**Comment by philippwaller** [comment]
agree

**Comment by ReneNulschDE** [comment]
Some older cars do not report heading... therefor, please remove lat or long from this list.

**Comment by ReneNulschDE** [comment]
Thx!

**Pull request merged**
